#logging:
#  level:
#    root: warn
#    com.rest.api: debug

spring:
  url:
    base: http://localhost:8080

#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    properties.hibernate:
#      hbm2ddl.auto: update
#      format_sql: true
#      use_sql_comments: true
#    show_sql: true
#    generate-ddl: true
#    open-in-view: false
  datasource:
    url: jdbc:h2:tcp://localhost:9092/mem:testdb;MODE=MySQL;
    username: sa
    password:
    driver-class-name: org.h2.Driver
    schema: classpath:schema.sql
    data: classpath:data.sql